//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolptManagment.БазаДанных
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applications
    {
        public int idApplication { get; set; }
        public string nameA { get; set; }
        public string surnameA { get; set; }
        public string patronymicA { get; set; }
        public Nullable<long> phonenumber { get; set; }
        public Nullable<long> passport { get; set; }
        public string nameSpecial { get; set; }
        public Nullable<int> avgRating { get; set; }
        public string statusA { get; set; }
        public Nullable<int> idSpec { get; set; }
    
        public virtual Specializations Specializations { get; set; }
    }
}
