//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolptManagment.БазаДанных
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class VoltptDBEntities : DbContext
    {
        private static VoltptDBEntities _context;
        public VoltptDBEntities()
            : base("name=VoltptDBEntities")
        {
        }

        public static VoltptDBEntities GetContext()
        {
            if (_context == null)
                _context = new VoltptDBEntities();

            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Applications> Applications { get; set; }
        public virtual DbSet<Exams> Exams { get; set; }
        public virtual DbSet<ExamsOrg> ExamsOrg { get; set; }
        public virtual DbSet<RatingsReceived> RatingsReceived { get; set; }
        public virtual DbSet<Specializations> Specializations { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<ResultExams> ResultExams { get; set; }
    }
}
