//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolptManagment.БазаДанных
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamsOrg
    {
        public int idExamsOrg { get; set; }
        public string namesubject { get; set; }
        public Nullable<System.DateTime> dateEO { get; set; }
        public string place { get; set; }
    }
}
