//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolptManagment.БазаДанных
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultExams
    {
        public int idResultExams { get; set; }
        public string nameRE { get; set; }
        public string surnameRE { get; set; }
        public string patronymicRE { get; set; }
        public string Subjectschool { get; set; }
        public Nullable<double> avgRatingRE { get; set; }
        public Nullable<int> idExams { get; set; }
    
        public virtual Exams Exams { get; set; }
    }
}
